const sData = [
  {
    id:"1",
    sName: "DARK",
    imgsrc: "https://wallpapercave.com/w/wp5770334.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80100172",
    watch: "Watch Now",
  },

  {
    id:"2",
    sName: "The Witcher",
    imgsrc: "https://wallpapercave.com/w/wp5410716.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80189685",
    watch: "Watch Now",
  },
  {
    id:"3",
    sName: "Stranger Things",
    imgsrc: "https://wallpapercave.com/w/wp10676647.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80057281",
    watch: "Watch Now",
  },

  {
    id:"4",
    sName: "Sacred Games",
    imgsrc: "https://wallpapercave.com/w/wp4555155.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80115328",
    watch: "Watch Now",
  },
  {
    id:"5",
    sName: "Peaky Blinders",
    imgsrc: "https://wallpapercave.com/w/wp9537129.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80002479",
    watch: "Watch Now",
  },
  {
    id:"6",
    sName: "Vampire Diaries",
    imgsrc: "https://wallpapercave.com/w/uwp2746604.jpg",
    title: "Amozon Original Series",
    link: "https://www.primevideo.com/detail/0HOK2IOF5E6RFUO8LL6L4LAW3W/?ref_=dvm_pds_gen_in_as_s_gm_dsafeedn_mkw_s-dc&mrntrk=pcrid_580613895533_slid__pgrid_120713930559_pgeo_21334_x_39528976673_adext__ptid_dsa-1354015554188&gclid=CjwKCAiAkrWdBhBkEiwAZ9cdcFADXcQb8_hLr9MhooNmTXkX92eOXqfmor4IzbYIYdDVw9DEL0sCnxoCpUEQAvD_BwE",
    watch: "Watch Now",
  },
  {
    id:"7",
    sName: "vikings",
    imgsrc: "https://wallpapercave.com/w/wp7994370.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/70301870",
    watch: "Watch Now",
  },
  {
    id:"8",
    sName: "DARK",
    imgsrc: "https://wallpapercave.com/w/wp5770334.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80100172",
    watch: "Watch Now",
  },

  {
    id:"9",
    sName: "The Witcher",
    imgsrc: "https://wallpapercave.com/w/wp5410716.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80189685",
    watch: "Watch Now",
  },
  {
    id:"10",
    sName: "Stranger Things",
    imgsrc: "https://wallpapercave.com/w/wp10676647.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80057281",
    watch: "Watch Now",
  },

  {
    id:"11",
    sName: "Sacred Games",
    imgsrc: "https://wallpapercave.com/w/wp4555155.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80115328",
    watch: "Watch Now",
  },
  {
    id:"12",
    sName: "Peaky Blinders",
    imgsrc: "https://wallpapercave.com/w/wp9537129.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80002479",
    watch: "Watch Now",
  },
  {
    id:"13",
    sName: "Breaking Bad",
    imgsrc: "https://wallpapercave.com/w/wp5311802.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/70143836",
    watch: "Watch Now",
  },
  {
    id:"14",
    sName: "vikings",
    imgsrc: "https://wallpapercave.com/w/wp7994370.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/70301870",
    watch: "Watch Now",
  },
  {
    id:"15",
    sName: "DARK",
    imgsrc: "https://wallpapercave.com/w/wp5770334.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80100172",
    watch: "Watch Now",
  },

  {
    id:"16",
    sName: "The Witcher",
    imgsrc: "https://wallpapercave.com/w/wp5410716.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80189685",
    watch: "Watch Now",
  },
  {
    id:"17",
    sName: "Stranger Things",
    imgsrc: "https://wallpapercave.com/w/wp10676647.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80057281",
    watch: "Watch Now",
  },

  {
    id:"18",
    sName: "Sacred Games",
    imgsrc: "https://wallpapercave.com/w/wp4555155.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80115328",
    watch: "Watch Now",
  },
  {
    id:"19",
    sName: "Peaky Blinders",
    imgsrc: "https://wallpapercave.com/w/wp9537129.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/80002479",
    watch: "Watch Now",
  },
  {
    id:"20",
    sName: "Breaking Bad",
    imgsrc: "https://wallpapercave.com/w/wp5311802.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/70143836",
    watch: "Watch Now",
  },
  {
    id:"21",
    sName: "vikings",
    imgsrc: "https://wallpapercave.com/w/wp7994370.jpg",
    title: "A Netflix Original Series",
    link: "https://www.netflix.com/in/title/70301870",
    watch: "Watch Now",
  }
];

export default sData;
